view_node(N, N) :- node(N, K, L, S).
view_group(G, L) :- group(G, L).
view_contains(G, K, I, 10) :- contains(G, K, I).
view_edge(E, E, A, B) :- edge(E, K, A, B, L, D), view_node(A, A), view_node(B, B).

view_style("node", N, "stroke", "#475569", 10) :- view_node(N, E).
view_style("node", N, "stroke", "#dc2626", 50) :- node(N, K, L, "hexagon").
view_style("group", G, "stroke", "#0f172a", 10) :- view_group(G, L).
view_style("edge", E, "stroke", "#2563eb", 10) :- view_edge(E, R, A, B).
